services:
    server:
        container_name: w-backend
        build:
            context: .
            dockerfile: "docker/Backend"
        volumes:
            - ./:/var/www/html
            - ./docker/config/php:/usr/local/etc/
        ports:
            - 9000:80
        depends_on:
            -   mysql_db

#    client:
#        container_name: w-frontend
#        build:
#            context: ./vue
#            dockerfile: ../docker/Frontend
#        volumes:
#            - ./vue/:/var/www/html/
#            - /var/www/html/node_modules
#        ports:
#            - "9090:8080"
#        depends_on:
#            - server
#        restart: always

    mysql_db:
        container_name: w-mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: word_score
        ports:
            - 3007:3306

    phpmyadmin:
        container_name: w-phpmyadmin
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
